#!/usr/bin/env python3
"""
update_trend_scores.py
Earth HRC Index — update trend_score in Supabase from GEE export CSVs.

Usage:
  python3 scripts/update_trend_scores.py path/to/HRC_Wales_Trend_60months.csv

What it does:
  1. Reads the CSV exported from Google Earth Engine
  2. Generates SQL UPDATE statements matching tiles by rounded coordinates
  3. Saves a .sql file you can paste into the Supabase SQL Editor

Output file: scripts/update_trend_<region>.sql
"""

import csv
import sys
import os
from pathlib import Path

def csv_to_sql(csv_path: str) -> str:
    csv_path = Path(csv_path)
    if not csv_path.exists():
        print(f"Error: file not found: {csv_path}")
        sys.exit(1)

    # Derive a label from the filename for the output file
    region_label = csv_path.stem  # e.g. "HRC_Wales_Trend_60months"
    output_path = Path(__file__).parent / f"update_trend_{region_label}.sql"

    rows = []
    with open(csv_path, newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                lon        = float(row['longitude'])
                lat        = float(row['latitude'])
                trend      = row['trend_score'].strip()

                # Skip rows where trend is missing or not a number
                if trend in ('', 'null', 'NULL', 'None'):
                    continue
                trend_val = float(trend)

                rows.append((lon, lat, trend_val))
            except (KeyError, ValueError) as e:
                print(f"Skipping row (parse error: {e}): {row}")
                continue

    if not rows:
        print("No valid rows found in CSV. Check the file and column names.")
        sys.exit(1)

    print(f"  Parsed {len(rows)} rows from {csv_path.name}")

    # Build SQL
    lines = [
        "-- ============================================================",
        f"-- HRC Index — update trend scores from: {csv_path.name}",
        f"-- Generated by update_trend_scores.py",
        f"-- Tiles matched by coordinates rounded to 4 decimal places",
        "-- Paste this entire block into Supabase SQL Editor and click Run",
        "-- ============================================================",
        "",
        "BEGIN;",
        "",
    ]

    matched = 0
    for lon, lat, trend in rows:
        # Round to 4 decimal places — matches ERA5 grid precision
        lon_r = round(lon, 4)
        lat_r = round(lat, 4)

        lines.append(
            f"UPDATE hrc_tiles"
            f" SET trend_score = {trend}"
            f" WHERE ROUND(longitude::numeric, 4) = {lon_r}"
            f" AND ROUND(latitude::numeric, 4) = {lat_r};"
        )
        matched += 1

    lines += [
        "",
        "COMMIT;",
        "",
        f"-- {matched} UPDATE statements generated",
        f"-- After running, verify with:",
        f"-- SELECT COUNT(*), AVG(trend_score), MIN(trend_score), MAX(trend_score)",
        f"-- FROM hrc_tiles;",
    ]

    sql_text = "\n".join(lines)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_text)

    print(f"  SQL file written: {output_path}")
    return str(output_path)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("\nError: please provide the path to the CSV file.")
        print("Example: python3 scripts/update_trend_scores.py ~/Downloads/HRC_Wales_Trend_60months.csv")
        sys.exit(1)

    csv_path = sys.argv[1]
    print(f"\nProcessing: {csv_path}")
    output = csv_to_sql(csv_path)

    print(f"\nDone. Next steps:")
    print(f"  1. Open your Supabase dashboard: https://supabase.com/dashboard")
    print(f"  2. Select project earth-hrc-index")
    print(f"  3. Go to SQL Editor (left sidebar)")
    print(f"  4. Open the file: {output}")
    print(f"  5. Copy all the text and paste it into the SQL Editor")
    print(f"  6. Click Run")
    print(f"  7. You should see 'Success. X rows affected'")


if __name__ == '__main__':
    main()
